# 1: NUMPY

A Numpy array is a collection of similar data type values, and is indexed by a tuple of nonnegative numbers. 
Import library numpy as object np.

In [1]:
import numpy as np

The rank of the array is the number of dimensions in the given array.
Here we are creating an array a={0,1,2} and printing its data tupe which is n dimensional array of class numpy.

In [2]:
a=np.array([0,1,2])
print(type(a))

<class 'numpy.ndarray'>


The shape of an array is a tuple of numbers giving the size of the array along each dimension.
Indexing is used to print a particular character and it starts from to n-1 where n is no of elements in an array.

In [3]:
print(a.shape)
print(a[0])
print(a[1])
print(a[2])

(3,)
0
1
2


The given command is used to replace an element of an array of patrticular index with given element.

In [4]:
a[0] = 5
print(a)

[5 1 2]


Here an array with two rows and three columns (2X3) is constructed and stored in an array as seen from the shape comman given to array.
Here elements are acessed by indexing by synatx array[row_index,column_index]

In [5]:
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


It creates a 3X3 array is constructed with all of its elements as zeros.
They are storede as float value by default.

In [6]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


It creates a 3X3 array is constructed with all of its elements as ones.
They are all stored as float value by default.

In [7]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


It creates a 3X3 array as 7 as all of its elements.
In other words a constant 3X3 array with 7 as its only element at all positions.

In [8]:
c = np.full((3,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


It creates a 3X3 array with random values.
Random function is used to generate random values.

In [9]:
d = np.random.random((3,3))
print(d)

[[0.82193026 0.77307451 0.01233045]
 [0.10976293 0.17017    0.96589267]
 [0.85734729 0.77200686 0.5696631 ]]


It creates a 3X3 array as identity array. Here only one number is given as parameter and a square matrix of that size is made.
Identity array or matrix is a square array or matrix with all of its diagonal elements asone and rest elements as zero.

In [10]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Here a list of numbers is getting converted to an array. List of numbers [2,3,1,0] is stored in an array f and then printed.

In [11]:
f = np.array([2, 3, 1, 0])
print(f)

[2 3 1 0]


Here an array is constructed all the integer elemnts from 0 to n-1 where n is the number mentioned in parameter of arange function.

In [12]:
g = np.arange(20)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Here a 3X3 array with complex numbers is constructed with one of the complex number stored in tuple. It converts all numbers in list and tuples to array.The number is stored with real as well as imaginary part.

In [13]:
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


It is used to create an array with elements ranging from 0 to n-1 where n is no of elements in array with data type as float.

In [14]:
i = np.arange(1, 8, dtype=np.float)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


It is used to create an array with 5 elements strating from 2 and stop at 4. Its synatx is array=np.linspace(start,stop,no_of_elements).

In [15]:
j = np.linspace(2, 4, 5)
print(j)

[2.  2.5 3.  3.5 4. ]


It is used to create an array with default data type which machine does implicitly. The data type is selected implicitly according to the input given in the arrays.

In [16]:
x = np.array([0, 1])
y = np.array([2.0, 3.0])
print (x.dtype)
print (y.dtype)

int32
float64


Here a particular data type is given to array to store data as particular data type in array.

In [17]:
z = np.array([5, 6], dtype=np.int64)
print (z.dtype)

int64


It is used to create a new array temp from an exsting array arr with elements from first two rows and alternate columns zero and two.

In [18]:
arr = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


It is used to create an array temp from array arr with first parameter as list of row indices and second parameter as list of column indices.

In [19]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


It is used to create a variable cond which stores indices of all alents greater than zero and then supply it to temp array to store these elemnts of array to store in temp array and then print elements greater than zero.

In [20]:
cond = arr > 0 
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


It is used to create an array 'a' and perform some arithmetic operations on it like addition,substraction,multiplication and many more.

In [21]:
a = np.array([1, 2, 5, 3])
# add 1 to every element
print ("Adding 1 to every element:", a+1)
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
# square each element
print ("Squaring each element:", a**2)
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]


It is used to find transpose of a given 3X3 array 'a' using a.T opertaion.

In [22]:
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)


Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


Here various operations are performed to find maximum and minimum elemnts in an array,maximum and minimum elements row wise and sum of all elements in array as well as row wise. For row wise operations additional parameter of axis=1 is added to consider one dimension at a time.

In [23]:
arr = np.array([[1, 5, 6],[4, 7, 2],[3, 1, 9]])
# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
# minimum element of array
print ("Column-wise minimum elements:",arr.min(axis = 0))
# sum of array elements
print ("Sum of all array elements:",arr.sum())
# cumulative sum along each row
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


Here two arrays 'a' and 'b' of size 2X2 are constructed and arithmetic operations are performed on it.'a*b' will perform multiplication elementwise like a(0,0) element with b(0,0), a(1,1) with b(1,1) and so on. To perform matrix multiplication command used is 'a.dot(b)'.

In [24]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[4, 3],[2, 1]])
# add arrays
print ("Array sum:\n", a + b)
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


Here various mathematical functions like sin function,exponent function and square root function is applied to an array 'a'. The output is given by applying these functions to all the elements of the array and storing them in a resultant array. 

In [25]:
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


Here inverse of array or matrix 'arr' is found using built in function with syntax inverse=np.linalg.inv(array).

In [26]:
arr = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
print(inverse)

[[ 4.05707196  1.98511166 -2.28287841  1.01736973]
 [ 0.50620347  0.30272953 -0.24813896 -0.01985112]
 [-2.66253102 -1.13151365  1.50124069 -0.67990074]
 [ 1.01116625  0.34491315 -0.44665012  0.26426799]]


Various matrix and dot products using numpy library.
Here we are finding product, dot product, outer product, Tensor product,Einsum, Einsum path and value of matrix raised to certain power.Here we are using two 4X4 matrix.

In [27]:
arr1 = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])
arr2 = np.array([[1, 5, 6, 12],[4, 7, 2, -5],[3, 1, 9, 2.4],[7, 8, 3, 4]])
prod = np.linalg.multi_dot([arr1,arr2])
print("Product :\n",prod) #the dot product of two or more arrays in a single function call.
print("\nDot product =",np.vdot(arr1,arr2)) #Return the dot product of two vectors.
print("\nOuter product :\n",np.outer(arr1,arr2)) #Compute the outer product of two vectors.
print("\nMatrix product :\n",np.matmul(arr1,arr2)) #Matrix product of two arrays.
print("\nTensor product =",np.tensordot(arr1,arr2)) #Compute tensor dot product along specified axes for arrays >= 1-D.
print("\nEinsum =",np.einsum('ii->i',arr1))   #Evaluates the Einstein summation convention on the operands.
print("\nEinsum path =",np.einsum_path('ii->i',arr1)) #Evaluates the lowest cost contraction order for an einsum expression by considering the creation of intermediate arrays.
print("\nCube :\n",np.linalg.matrix_power(arr2,3))#Raise a square matrix to the (integer) power n.

Product :
 [[ 35.   41.   10.   -6. ]
 [ 20.   22.5  77.   64.9]
 [ 79.6  84.  102.6  80. ]
 [  1.  -14.   46.   88.6]]

Dot product = 156.5

Outer product :
 [[ -1.    -5.    -6.   -12.    -4.    -7.    -2.     5.    -3.    -1.
   -9.    -2.4   -7.    -8.    -3.    -4.  ]
 [  2.    10.    12.    24.     8.    14.     4.   -10.     6.     2.
   18.     4.8   14.    16.     6.     8.  ]
 [  0.     0.     0.     0.     0.     0.     0.    -0.     0.     0.
    0.     0.     0.     0.     0.     0.  ]
 [  4.    20.    24.    48.    16.    28.     8.   -20.    12.     4.
   36.     9.6   28.    32.    12.    16.  ]
 [  4.    20.    24.    48.    16.    28.     8.   -20.    12.     4.
   36.     9.6   28.    32.    12.    16.  ]
 [ -0.5   -2.5   -3.    -6.    -2.    -3.5   -1.     2.5   -1.5   -0.5
   -4.5   -1.2   -3.5   -4.    -1.5   -2.  ]
 [  6.    30.    36.    72.    24.    42.    12.   -30.    18.     6.
   54.    14.4   42.    48.    18.    24.  ]
 [  0.     0.     0.     0.     0. 

Eigen values and eigen vectors for various matrices.
Here we are finding right as well as Hermitian eigen values and eigen vectors for the given 4X4 matrix.

In [28]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("Right Eigen values and eigen vectors :\n",np.linalg.eig(a))  #Compute the eigenvalues and right eigenvectors of a square array.
print("Hermitian Eigen values and eigen vectors :\n",np.linalg.eigh(a))  #Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or areal symmetric matrix.
print("Eigen values =",np.linalg.eigvals(a)) #Compute the eigenvalues of a general matrix.

Right Eigen values and eigen vectors :
 (array([ 3.62093727e+01, -2.20937271e+00, -2.91421324e-15, -5.70557534e-16]), array([[-0.15115432,  0.72704996, -0.36400894,  0.00610215],
       [-0.34923733,  0.28320876,  0.79039305,  0.40008675],
       [-0.54732033, -0.16063243, -0.4887593 , -0.81847996],
       [-0.74540333, -0.60447363,  0.06237518,  0.41229105]]))
Hermitian Eigen values and eigen vectors :
 (array([-7.67424525, -1.52933936, -0.88700734, 44.09059195]), array([[-0.72700464,  0.52223568, -0.27042086,  0.35441037],
       [-0.38475626, -0.47667819,  0.66785887,  0.4227352 ],
       [ 0.10790023, -0.54052519, -0.65266639,  0.51982367],
       [ 0.55837659,  0.45593895,  0.23422994,  0.65228183]]))
Eigen values = [ 3.62093727e+01 -2.20937271e+00 -2.91421324e-15 -5.70557534e-16]


Submitted By:
Sachin Rawat
RA1912039010003
M.Tech Big Data Analytics